filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: false

